# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txaNfetLjqq32InNKCMhn4n2401g3fbB
"""

import pandas as pd
talaba=pd.DataFrame({
    "FISH" : [ 'Topivoldiyev Abbosbek','Pozilov Abdulaziz','Zaripov Habibulloh','Usmonov Muhammadyusuf','Saydahmadov Zohidjon','Mamasoliyev Asilbek','Abduhoshimov Shaxriyor', 'Abdullayev Shaxriyor' ,'Aliyev Abdulvosit', 'Abdurahmonov Doniyorbek'],
    "Guruhi" : [ '681-23' , '681-23', '613-23', '681-23', '510-23','681-23','681-23','681-23','681-23','681-23' ],
    "Tug'ilgan sana" : [ '12.02.2005', '15.03.2005','07.12.2004','16.08.2005','04.01.2005', '25.10.2005','14.06.2005','30.11.2005','20.03.2005','12.06.2005'  ],
    "Telefon raqami" : [ '+998991801071', '+998991234567','+998975544749','+998991004694','+998999456321','+998333333113','+998774656456','+998501254657','+998204546655','+998994445500'   ]

})
print(talaba)

talaba.to_excel('talabalar.xlsx')